FROM ruby:3.3-slim
WORKDIR /app
RUN apt-get update -y && apt-get install -y --no-install-recommends build-essential libpq-dev git pkg-config libyaml-dev && rm -rf /var/lib/apt/lists/*
COPY Gemfile Gemfile.lock /app/
ENV BUNDLE_PATH=/usr/local/bundle \
    BUNDLE_WITHOUT=production
RUN bundle install
CMD ["bash", "-lc", "bundle check || bundle install && bundle exec rails server -b 0.0.0.0 -p 3000"]
