FROM ruby:3.3-slim
WORKDIR /app
RUN apt-get update -y && apt-get install -y --no-install-recommends build-essential libpq-dev git pkg-config libyaml-dev && rm -rf /var/lib/apt/lists/*
COPY Gemfile Gemfile.lock /app/
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
ENV BUNDLE_PATH=/usr/local/bundle \
    BUNDLE_WITHOUT=production
RUN bundle install
CMD ["/usr/bin/env", "bash", "/usr/local/bin/entrypoint.sh"]
